version: '3'

services:
  fluent:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "cd /app; npm install; npm run test-postgres"
    depends_on:
      - db_host

  db_host:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
